Javascript loops practice - Alvin Cho
c-alvin/c0622-code-solutions pull request #35
Opened 2022-07-08 22:06 UTC by c-alvin

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/106632915/178076184-f36279be-f8f7-4b1c-ab78-7d0506ea2833.png">

2022-07-08 22:36 UTC, codingcodymiller requested changes

2022-07-08 22:36 UTC, codingcodymiller commented on javascript-loops-practice/filter-out-nulls.js
> +    if (values[i] != null) {
strictly equals or strictly not equals only, please 👀

2022-07-09 00:20 UTC, c-alvin commented
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/106632915/178084260-446d7fbf-63d1-4a3a-89eb-7a5123835d10.png">

2022-07-11 17:44 UTC, codingcodymiller approved these changes

2022-07-11 17:50 UTC, merged