javascript-forms - Alvin Cho
c-alvin/c0622-code-solutions pull request #48
Opened 2022-07-13 19:44 UTC by c-alvin

![image](https://user-images.githubusercontent.com/106632915/178818362-85aba906-3e96-4178-acb4-dced0863b336.png)

2022-07-13 22:38 UTC, codingcodymiller requested changes

2022-07-13 22:38 UTC, codingcodymiller commented on javascript-forms/form-events.js
> +var $inputTwo = document.forms[0].elements[1];
Just use `querySelector` 😂

2022-07-14 00:34 UTC, c-alvin commented
![image](https://user-images.githubusercontent.com/106632915/178859816-122b3465-5909-4e19-83d9-b409514e290f.png)

2022-07-14 18:34 UTC, codingcodymiller approved these changes

2022-07-14 19:23 UTC, merged