Completed express-notes-api - Alvin Cho
c-alvin/c0622-code-solutions pull request #90
Opened 2022-08-22 22:58 UTC by c-alvin

![image](https://user-images.githubusercontent.com/106632915/186033127-2e8a4a1e-c797-4090-8b02-9016e2c6e80e.png)

2022-08-22 23:12 UTC, TimelikeClosure requested changes

2022-08-22 23:12 UTC, TimelikeClosure commented on express-notes-api/data.json
> +    }
The content you write to `data.json` should have the same format as the pre-existing records.

2022-08-22 23:12 UTC, TimelikeClosure commented on express-notes-api/index.js
> +  }
What if the number is `0`? Or a non-whole number? Or not a number to begin with?

2022-08-22 23:12 UTC, TimelikeClosure commented on express-notes-api/index.js
> +  }
There shouldn't be any way that the a request can skip every possible response.

2022-08-22 23:12 UTC, TimelikeClosure commented on express-notes-api/index.js
> +  const Object = req.body;
Overwriting built-in globals is _baaaaaaaad_.

2022-08-22 23:46 UTC, TimelikeClosure requested changes

2022-08-22 23:46 UTC, TimelikeClosure commented on express-notes-api/index.js
> +  }
`res.send()` does not exit the middleware function on its own, so make sure you find some way to prevent multiple responses from being sent.

2022-08-22 23:46 UTC, TimelikeClosure commented on express-notes-api/index.js
> +    notes[data.nextId] = Object;
`Object` is a built-in constructor function. Please make sure you're assigning the actual note data.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object

2022-08-23 00:07 UTC, TimelikeClosure requested changes
@c-alvin Please include a screenshot verifying _every_ route responds correctly as in each of the example cases.

2022-08-23 00:32 UTC, c-alvin commented
![expressnotes1](https://user-images.githubusercontent.com/106632915/186042880-03e5e48d-ed5a-4a96-bf73-c9c462224575.gif)
![expressnotesapi2](https://user-images.githubusercontent.com/106632915/186042887-cb5ac307-73d4-4bb2-aa30-8cb01655dcbe.gif)

2022-08-23 00:41 UTC, TimelikeClosure requested changes

2022-08-23 00:41 UTC, TimelikeClosure commented on express-notes-api/index.js
> +      JSON.error = 'An unexpected error occurred.';
Please don't add properties to the global `JSON` object: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON

2022-08-23 00:55 UTC, c-alvin commented
![expressnotes500](https://user-images.githubusercontent.com/106632915/186045004-0bd00343-e03c-4603-b6ac-25ebdda87bdd.gif)

2022-08-23 02:23 UTC, c-alvin commented
![express-notes-apifinal](https://user-images.githubusercontent.com/106632915/186054958-80ef1909-2055-4ce5-98a8-4cbe3fb0df35.gif)

2022-08-23 20:11 UTC, TimelikeClosure approved these changes

2022-08-25 17:40 UTC, merged